# Generated by Django 6.0.6 on 2026-06-22 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(blank=True, max_length=100, null=True)),
                ('guest_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('order_type', models.CharField(choices=[('purchase', 'New Bottle Purchase'), ('refill', 'Water Refill')], max_length=20)),
                ('size', models.IntegerField(choices=[(5, '5L'), (10, '10L'), (20, '20L')])),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('preparing', 'Preparing'), ('dispatched', 'Dispatched'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mpesa_receipt', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_phone', models.CharField(blank=True, max_length=20)),
                ('delivery_address', models.TextField()),
                ('delivery_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
