# Generated by Django 6.0.5 on 2026-05-27 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(choices=[(5, '5 Litres'), (10, '10 Litres'), (20, '20 Litres')])),
                ('bottle_code', models.CharField(max_length=20, unique=True)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(choices=[(5, '5 Litres'), (10, '10 Litres'), (20, '20 Litres')], unique=True)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('refill_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
