# Generated by Django 6.0.5 on 2026-05-27 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bottle',
            name='bottle_code',
        ),
    ]
