# Generated by Django 6.0.6 on 2026-06-26 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bottle',
            name='user',
        ),
    ]
